#include "adc_2.h"

void adc_2_gpio_init(void) {
	
	/* CONFIGURE INPUT PINS */
	/*
		PORT A PINS 6 AND 7 ARE USED FOR ADC 
		CHANNELS 6 AND 7. THEY ARE CONFIGURED AS
		ANALOG MODE, NO PULL-UP/PULL-DOWN.
	*/
	
	// ENABLE PORT A CLOCK
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	
	/* SET AS ANALOG */
	
	// PA6
	GPIOA->MODER |= (3 << 6*2);
	
	// PA7
	GPIOA->MODER |= (3 << 7*2);
	
	/* SET AS NO PULL-UP/PULL-DOWN */
	
	// PA6
	GPIOA->PUPDR &= ~(3 << 6*2);
	
	// PA7
	GPIOA->PUPDR &= ~(3 << 7*2);
	
}

void adc_2_config(void) {
	
	/*
		ADC_2 WILL SAMPLE FROM TWO SOURCES,
		CHANNEL 6 AND 7. THE ADC WILL NOT USE SCAN
		MODE, CHANNELS MUST BE SELECTED MANUALLY
		BY CONFIGURING WHICH CHANNEL THE ADC SAMPLES
		FROM USING THE SQR3 REGISTER. CHANNEL 6 WILL
		BE THE INITIAL CHANNEL SELECTED
	*/
		
	// ENABLE ADC
	RCC->APB2ENR |= RCC_APB2ENR_ADC2EN;
	
	// DISABLE CONVERSION
	ADC2->CR2 &= ~ADC_CR2_ADON;
	
	// CONFIGURE REGULAR CHANNEL SEQUENCE LENGTH TO 1 CONVERSION
	ADC2->SQR1 &= ~ADC_SQR1_L;
	
	// SELECT CHANNEL 6 AS FIRST AND ONLY CONVERSION
	ADC2->SQR3 |= 6;
	
	// SELECT 16 CYCLES PER SAMPLE FOR CONVERSION
	ADC2->SMPR1 |= 0x2;
	
	// ENABLE END OF CONVERSION INTERRUPT
	ADC2->CR1 |= ADC_CR1_EOCIE;
	
	// ENABLE ADC
	ADC2->CR2 |= ADC_CR2_ADON;
	
}


