#include "adc_3.h"


void adc_3_config(void) {
	
	/*
		WRITE A NEW NOTE SOMETIME
	*/
		
	// ENABLE ADC
	RCC->APB2ENR |= RCC_APB2ENR_ADC3EN;
	
	// DISABLE CONVERSION
	ADC3->CR2 &= ~ADC_CR2_ADON;
	
	// CONFIGURE REGULAR CHANNEL SEQUENCE LENGTH TO 1 CONVERSION
	ADC3->SQR1 &= ~ADC_SQR1_L;
	
	// SELECT CHANNEL 6 AS FIRST AND ONLY CONVERSION
	ADC3->SQR3 |= 12;
	
	// SELECT 144 CYCLES PER SAMPLE FOR CONVERSION
	ADC3->SMPR1 |= (6 << 12);
	
	// ENABLE END OF CONVERSION INTERRUPT
	ADC3->CR1 |= ADC_CR1_EOCIE;
	
	// ENABLE ADC
	ADC3->CR2 |= ADC_CR2_ADON;
	
}


