#include "adc_2.h"

void adc_2_config(void) {
	
	/*
		WRITE A NEW NOTE SOMETIME
	*/
		
	// ENABLE ADC
	RCC->APB2ENR |= RCC_APB2ENR_ADC2EN;
	
	// DISABLE CONVERSION
	ADC2->CR2 &= ~ADC_CR2_ADON;
	
	// CONFIGURE REGULAR CHANNEL SEQUENCE LENGTH TO 1 CONVERSION
	ADC2->SQR1 &= ~ADC_SQR1_L;
	
	// SELECT CHANNEL 6 AS FIRST AND ONLY CONVERSION
	ADC2->SQR3 |= 8;
	
	// SELECT 144 CYCLES PER SAMPLE FOR CONVERSION
	ADC2->SMPR1 |= (6 << 12);
	
	// ENABLE END OF CONVERSION INTERRUPT
	ADC2->CR1 |= ADC_CR1_EOCIE;
	
	// ENABLE ADC
	ADC2->CR2 |= ADC_CR2_ADON;
	
}


