#include "adc_1.h"

void adc_1_gpio_init(void) {
	
	/* CONFIGURE INPUT PINS */
	/*
		PORT A PINS 4 AND 5 ARE USED FOR ADC 
		CHANNELS 4 AND 5. THEY ARE CONFIGURED AS
		ANALOG MODE, NO PULL-UP/PULL-DOWN.
	*/
	
	// ENABLE PORT A CLOCK
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	
	/* SET AS ANALOG */
	
	// PA4
	GPIOA->MODER |= (3 << 4*2);
	
	// PA5
	GPIOA->MODER |= (3 << 5*2);
	
	/* SET AS NO PULL-UP/PULL-DOWN */
	
	// PA4
	GPIOA->PUPDR &= ~(3 << 4*2);
	
	// PA5
	GPIOA->PUPDR &= ~(3 << 5*2);
	
}

void adc_1_config(void) {
	
	/*
		ADC_1 WILL SAMPLE FROM TWO SOURCES,
		CHANNEL 4 AND 5. THE ADC WILL NOT USE SCAN
		MODE, CHANNELS MUST BE SELECTED MANUALLY
		BY CONFIGURING WHICH CHANNEL THE ADC SAMPLES
		FROM USING THE SQR3 REGISTER. CHANNEL 4 WILL
		BE THE INITIAL CHANNEL SELECTED
	*/
		
	// ENABLE ADC
	RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;
	
	// DISABLE CONVERSION
	ADC1->CR2 &= ~ADC_CR2_ADON;
	
	// CONFIGURE REGULAR CHANNEL SEQUENCE LENGTH TO 1 CONVERSION
	ADC1->SQR1 &= ~ADC_SQR1_L;
	
	// SELECT CHANNEL 4 AS FIRST AND ONLY CONVERSION
	ADC1->SQR3 |= 4;
	
	// SELECT 144 CYCLES PER SAMPLE FOR CONVERSION
	ADC1->SMPR2 |= (6 << 12);
	
	// ENABLE END OF CONVERSION INTERRUPT
	ADC1->CR1 |= ADC_CR1_EOCIE;
	
	// ENABLE ADC
	ADC1->CR2 |= ADC_CR2_ADON;
	
}


