#include "adc_3.h"

void adc_3_gpio_init(void) {
	
	/* CONFIGURE INPUT PINS */
	/*
		PORT C PIN 0 IS USED BY ADC_3 TO DO A SINGLE
		CONVERSION ON CHANNEL 10. IT IS CONFIGURED AS
		ANALOG MODE, NO PULL-UP/PULL-DOWN.
	*/
	
	// ENABLE PORT A CLOCK
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	
	/* SET AS ANALOG */
	
	// PC0
	GPIOC->MODER |= (3 << 0*2);
	
	/* SET AS NO PULL-UP/PULL-DOWN */
	
	// PC0
	GPIOC->PUPDR &= ~(3 << 0*2);
	
}

void adc_3_config(void) {
	
	/*
		ADC_3 WILL CONVERT A SINGLE
		SAMPLE ON ADC CHANNEL 10.
	*/
		
	// ENABLE ADC
	RCC->APB2ENR |= RCC_APB2ENR_ADC3EN;
	
	// DISABLE CONVERSION
	ADC3->CR2 &= ~ADC_CR2_ADON;
	
	// CONFIGURE REGULAR CHANNEL SEQUENCE LENGTH TO 1 CONVERSION
	ADC3->SQR1 &= ~ADC_SQR1_L;
	
	// SELECT CHANNEL 6 AS FIRST AND ONLY CONVERSION
	ADC3->SQR3 |= 10;
	
	// SELECT 16 CYCLES PER SAMPLE FOR CONVERSION
	ADC3->SMPR1 |= 0x2;
	
	// ENABLE END OF CONVERSION INTERRUPT
	ADC3->CR1 |= ADC_CR1_EOCIE;
	
	// ENABLE ADC
	ADC3->CR2 |= ADC_CR2_ADON;
	
}


