#include "adc_1.h"

void adc_1_config(void) {
	
	/*
		ADD A NEW NOTE SOMETIME
	*/
		
	// ENABLE ADC
	RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;
	
	// DISABLE CONVERSION
	ADC1->CR2 &= ~ADC_CR2_ADON;
	
	// CONFIGURE REGULAR CHANNEL SEQUENCE LENGTH TO 1 CONVERSION
	ADC1->SQR1 &= ~ADC_SQR1_L;
	
	// SELECT CHANNEL 4 AS FIRST AND ONLY CONVERSION
	ADC1->SQR3 |= 4;
	
	// SELECT 144 CYCLES PER SAMPLE FOR CONVERSION
	ADC1->SMPR2 |= (6 << 12);
	
	// ENABLE END OF CONVERSION INTERRUPT
	ADC1->CR1 |= ADC_CR1_EOCIE;
	
	// ENABLE ADC
	ADC1->CR2 |= ADC_CR2_ADON;
	
}


