#include "tim_10.h"

void tim_10_config(void){
	
	// ENABLE TIMER 12 CLOCK
	RCC->APB2ENR |= RCC_APB2ENR_TIM10EN;
	
	// TIMER 12 PRESCALER FOR 20KHz FREQ
	TIM10->PSC &= ~TIM_PSC_PSC;
	TIM10->PSC |= 1000;
	
	// AUTO RELOAD REGISTER
	TIM10->ARR &= ~TIM_ARR_ARR;
	TIM10->ARR |= 16000;
	
	// ENABLE AUTO RELOAD
	TIM10->CR1 |= TIM_CR1_ARPE;
	
	// ENABLE UPDATE EVENT INTERRUPT
	TIM10->DIER |= TIM_DIER_UIE;
	
	// ENABLE INTERRUPT
	NVIC_SetPriority(TIM1_UP_TIM10_IRQn, 2);
	NVIC_EnableIRQ(TIM1_UP_TIM10_IRQn);
	
	// ENABLE TIMER
	TIM10->CR1 |= TIM_CR1_CEN;
	
}