#include "tim_12.h"

#define AR_12 800 //auto reload value
#define PSC_12 0 // prescaler


void tim_12_gpio_init(void){
	
	/* CONFIGURE PWM PINS */
	/*
		PORT B PINS 14 AND 15 WILL BE CONFIGURED
		AS PUSH PULL, ALTERNATE FUNCTION FOR
		TIMER 12 AND NO PULL/PULL DOWN.
	*/
	
	// ENABLE GPIOB CLOCK
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
	
	/* SET AS PUSH PULL */
	
	// PB14
	GPIOB->OTYPER &= ~(1 << 14*1);
	
	// PB15
	GPIOB->OTYPER &= ~(1 << 15*1);
	
	/* SET AS ALTERNATE FUNCTION */
	
	// PB14
	GPIOB->MODER &= ~(3 << 14*2);
	GPIOB->MODER |= (2 << 14*2);
	
	// PB15
	GPIOB->MODER &= ~(3 << 15*2);
	GPIOB->MODER |= (2 << 15*2);
	
	/* SET AF AS TIM 12 */
	
	// PB14
	GPIOB->AFR[1] &= ~(0xF << (14-8)*4);
	GPIOB->AFR[1] |= (9 << (14-8)*4);
	
	// PB15
	GPIOB->AFR[1] &= ~(0xF << (15-8)*4);
	GPIOB->AFR[1] |= (9 << (15-8)*4);
	
	/* SET AS NO PULL-UP PULL-DOWN */
	
	// PB14
	GPIOB->PUPDR &= ~(3 << 14*2);
	
	// PB15
	GPIOB->PUPDR &= ~(3 << 15*2);
	
	/* CONFIGURE DIGITAL IO PINS */
	/*
		PORT A PIN 8 AND PORT C PIN 8 WILL SERVE AS THE
		LOW SIDE H-BRIDGE CONTROLS FOR THE
		TIMER 12 PWM CHANNELS.
	
		THEY ARE CONFIGURED AS PUSH PULL, GENERAL
		OUTPUT AND NO PULL-UP/PULL-DOWN.
	*/
	
	// ENABLE PORTA CLOCK
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	
	// ENABLE PORTC CLOCK
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	
	/* SET AS GENERAL PURPOSE OUTPUT */
	
	// PA8
	GPIOA->MODER &= ~(2 << 8*2);
	GPIOA->MODER |= (1 << 8*2);
	
	// PC8
	GPIOC->MODER &= ~(2 << 8*2);
	GPIOC->MODER |= (1 << 8*2);
	
	/* SET AS PUSH-PULL */
	
	// PA8
	GPIOA->OTYPER &= ~(1 << 8*1);
	
	// PC8
	GPIOC->OTYPER &= ~(1 << 8*1);
	
	/* SET AS NO PULL-UP/PULL-DOWN */
	
	// PA8
	GPIOA->PUPDR &= ~(2 << 8*2);
	
	// PC8
	GPIOC->PUPDR &= ~(2 << 8*2);
	
}


void tim_12_config(void){
	
	// ENABLE TIMER 12 CLOCK
	RCC->APB1ENR |= RCC_APB1ENR_TIM12EN;
	
	// TIMER 12 PRESCALER FOR 20KHz FREQ
	TIM12->PSC &= ~TIM_PSC_PSC;
	TIM12->PSC |= PSC_12;
	
	// AUTO RELOAD REGISTER
	TIM12->ARR &= ~TIM_ARR_ARR;
	TIM12->ARR |= AR_12;
	
	// CONFIGURE PWM MODE TO MODE 1 CHANNEL 1
	TIM12->CCMR1 &= ~(TIM_CCMR1_OC1M);
	TIM12->CCMR1 |= (TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1);
	
	// CONFIGURE PWM MODE TO MODE 1 CHANNEL 2
	TIM12->CCMR1 &= ~(TIM_CCMR1_OC2M);
	TIM12->CCMR1 |= (TIM_CCMR1_OC2M_2 | TIM_CCMR1_OC2M_1);
	
	// ENABLE AUTO RELOAD
	TIM12->CR1 |= TIM_CR1_ARPE;
	
	// PRELOAD CAPTURE COMPARE VALUE FOR CHANNEL 1
	TIM12->CCR1 |= 0;
	
	// PRELOAD CAPTURE COMPARE VALUE FOR CHANNEL 2
	TIM12->CCR2 |= 0;
	
	// ENABLE CHANNEL 1 OUTPUT
	TIM12->CCER |= TIM_CCER_CC1E;
	
	// ENABLE CHANNEL 2 OUTPUT
	TIM12->CCER |= TIM_CCER_CC2E;
	
	// ENABLE TIMER
	TIM12->CR1 |= TIM_CR1_CEN;
	
}
