#include "tim_5.h"

#define ARV 250000 //auto reload value
#define PSCVAL 96 // prescaler

	/* TIMER 5 Initialization */
void TIM_5_init(void){
	
	// ENABLE TIMER 5 CLOCK
	RCC->APB1ENR |= RCC_APB1ENR_TIM5EN;
	
	// TIMER 5 PRESCALER FOR 1MHz TIMER
	TIM5->PSC |= PSCVAL;
	
	// AUTO RELOAD REGISTER
	TIM5->ARR &= ~TIM_ARR_ARR;
	TIM5->ARR |= ARV;
	
	// CONFIGURE PWM MODE TO MODE 1 CHANNEL 1
	TIM5->CCMR1 &= ~(TIM_CCMR1_OC1M);
	TIM5->CCMR1 |= (TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1);
	
	// CONFIGURE PWM MODE TO MODE 1 CHANNEL 2
	TIM5->CCMR1 &= ~(TIM_CCMR1_OC2M);
	TIM5->CCMR1 |= (TIM_CCMR1_OC2M_2 | TIM_CCMR1_OC2M_1);
	
	// CONFIGURE PWM MODE TO MODE 1 CHANNEL 3
	TIM5->CCMR1 &= ~(TIM_CCMR2_OC3M);
	TIM5->CCMR1 |= (TIM_CCMR2_OC3M_2 | TIM_CCMR2_OC3M_1);
	
	// CONFIGURE PWM MODE TO MODE 1 CHANNEL 4
	TIM5->CCMR1 &= ~(TIM_CCMR2_OC4M);
	TIM5->CCMR1 |= (TIM_CCMR2_OC4M_2 | TIM_CCMR2_OC4M_1);
	
	// ENABLE AUTO RELAOD
	TIM5->CR1 |= TIM_CR1_ARPE;
	
	// ENABLE CHANNEL 1 OUTPUT
	TIM5->CCER |= TIM_CCER_CC1E;
	
	// ENABLE CHANNEL 2 OUTPUT
	TIM5->CCER |= TIM_CCER_CC2E;
	
	// ENABLE CHANNEL 3 OUTPUT
	TIM5->CCER |= TIM_CCER_CC3E;
	
	// ENABLE CHANNEL 4 OUTPUT
	TIM5->CCER |= TIM_CCER_CC4E;
	
	// PRELOAD CAPTURE COMPARE VALUE FOR CHANNEL 1
	TIM5->CCR1 |= 0;
	
	// PRELOAD CAPTURE COMPARE VALUE FOR CHANNEL 2
	TIM5->CCR2 |= 0;
	
	// PRELOAD CAPTURE COMPARE VALUE FOR CHANNEL 3
	TIM5->CCR3 |= 0;
	
	// PRELOAD CAPTURE COMPARE VALUE FOR CHANNEL 4
	TIM5->CCR4 |= 0;
	
	//ENABLE TIMER
	TIM5->CR1 |= TIM_CR1_CEN;
	
}	
